version: '3.8'

services:
  # Base de dades MySQL
  mysql:
    image: mysql:8.0
    container_name: quiz_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-quiz_banderas}
      MYSQL_USER: ${MYSQL_USER:-quiz_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quiz_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - quiz_network

  # Servidor web Nginx
  nginx:
    image: nginx:alpine
    container_name: quiz_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ..:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - quiz_network

  # PHP-FPM
  php:
    build: .
    container_name: quiz_php
    restart: unless-stopped
    volumes:
      - ..:/var/www/html
    depends_on:
      - mysql
    networks:
      - quiz_network

volumes:
  mysql_data:

networks:
  quiz_network:
    driver: bridge
